steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - source
      - repos
      - clone
      - github_nickhsine_kubernetes_configs
      - ./dockerignore/configs
  - name: bash
    args:
      - cp
      - ./dockerignore/configs/openwarehouse/overlays/dev/overlays/tv/overlays/cms/configs/config.js
      - ./configs/config.js
  - name: bash
    args:
      - cp
      - ./dockerignore/configs/openwarehouse/base/configs/gcskeyfile.json
      - ./configs/gcskeyfile.json
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/${PROJECT_ID}/openwarehouse:${BRANCH_NAME}_${SHORT_SHA}'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/openwarehouse
images:
  - gcr.io/$PROJECT_ID/openwarehouse

timeout: 900s
